### ISSUE TITLE
Minor Incompatability with Basic Weapons Mod

### ISSUE THREAD

**Issue by MagpieMaydin** [KermitEmperor/CuriosBackSlot#3] opened 2024-03-04 20:08 UTC
When The Quarter Staff and Spear from the [Basic Weapons mod](https://www.curseforge.com/minecraft/mc-mods/basic-weapons) are placed in the back weapon slot they render on the Front of the Player model instead of on the back. (across the chest and face)

**Comment by KermitEmperor** [comment] 2024-03-08 06:43
Duplicate of #2

**Closed as completed** 2024-03-08 06:43 UTC
Labels: duplicate, wontfix
